# Generated by Django 2.0 on 2019-06-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('event', models.CharField(blank=True, choices=[('product_created', 'Product Created'), ('product_updated', 'Product Updated')], max_length=200, null=True, verbose_name='Event to be triggered at')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('csv', 'Csv'), ('app', 'App')], default='app', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'description', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together={('url', 'event', 'name')},
        ),
    ]
